#server:
#  port: 4444
#spring:
#  application:
#    name: API-GATEWAY
#eureka:
#  client:
#    service-url:
#      defaultZone: ${DISCOVERY_URL:http://localhost:9090}/eureka/

#--- 
#eureka: 
#  client: 
#    service-url: 
#      defaultZone: "${DISCOVERY_URL:http://localhost:9090}/eureka/"
#server: 
#  port: 4444
#spring: 
#  application: 
#    name: API-GATEWAY









#--- 
#eureka: 
#  client: 
#    service-url: 
#      defaultZone: "${DISCOVERY_URL:http://localhost:9090}/eureka/"
#server: 
#  port: 4444
#spring: 
#  application: 
#    name: api-gateway
#  cloud: 
#    gateway: 
#      routes: 
#        - 
#          id: WELCOME-SERVICE
#          predicates: 
#            - Path=/first/**
#          uri: "Ib://WELCOME-SERVICE"
#        - 
#          id: GREET-SERVICE
#          predicates: 
#            - Path=/second/**
#          uri: "http://localhost:2222/"





--- 
eureka: 
  client: 
    service-url: 
      defaultZone: "${DISCOVERY_URL:http://localhost:9090}/eureka/"
server: 
  port: 4444
spring: 
  application: 
    name: API_GATEWAYE
  cloud: 
    gateway: 
      routes: 
        - 
          filters: 
            - StripPrefix=1
          id: WELCOME-SERVICE
          predicates: 
            - Path=/first/**
          uri: "lb://WELCOME-SERVICE"
        - 
          filters: 
            - StripPrefix=1
          id: GREET-MESSAGE
          predicates: 
            - Path=/second/**
          uri: "lb://GREET-MESSAGE"
          
        - 
          filters: 
            - StripPrefix=1
          id: WISH-MESSAGES
          predicates: 
            - Path=/third/**
          uri: "lb://WISH-MESSAGES"

